### ISSUE TITLE
How to use the compiled web component?

### ISSUE THREAD

**Issue by MuhsinFatih** [redradix/svelte-custom-element-template#1]
In `readme.md` it says:

> build: builds your app as a web component and outputs a minified and a normal version to /dist

I've created a simple html document `test/index.html` and tried to use this web component:
```svelte
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<script src="../dist/svelte-custom-element.0.1.0.min.js"></script>
<body>
	<svelte-custom-element></svelte-custom-element>
</body>
</html>
```

However I got this error:
```
Uncaught TypeError: Cannot read property 'insertRule' of null
    at ct (svelte-custom-element.0.1.0.min.js:1)
    at f (svelte-custom-element.0.1.0.min.js:1)
    at Object.run (svelte-custom-element.0.1.0.min.js:1)
    at svelte-custom-element.0.1.0.min.js:15
    at jt (svelte-custom-element.0.1.0.min.js:1)
    at Mt (svelte-custom-element.0.1.0.min.js:1)
    at new i (svelte-custom-element.0.1.0.min.js:15)
```

Am I missing something?

**Comment by MuhsinFatih** [comment]
I figured it out! (still have a follow-up question)
At first I didn't understand why `build:open` would serve files locally. I looked up how to import a web-component to see if I missed something, and realized that I'm missing the `type="module"` in script tag to import it as an ES6 module. That however gives a cors error because I'm trying to import a module from the file system. So I import from the local server:

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<script type="module" src="http://localhost:5000/svelte-custom-element.0.1.0.min.js"></script>
<body>
	<svelte-custom-element/>
</body>
</html>
```

Still CORS! The solution was to add `--cors` flag at the end of the `build:open` script:

```js
"build:open": "node ./scripts/build.js && serve dist --cors",
```

And it works!

![image](https://user-images.githubusercontent.com/8341386/103404215-c0c36680-4b20-11eb-9274-a04492f5d89b.png)

My question is, I want to import this in another project for example but I don't want to use the local server because that complicates the other project. Is this possible?

**Comment by MonkeyAndres** [comment]
Hi @MuhsinFatih,

You're right, I've had this serving logic because in an early version I was showing an example of how to integrate the component in a real HTML context.

In order to use the bundle in your project just create a `public` folder and put the web component built inside a `vendor` folder for example. The from the HTML import this file from the folder and add the attribute `defer`. There's no need for adding `type=module` and for using a local server, the component works without a local server.

I will remove the `build:open` script and add some usage instructions to README.

Thanks!!
