### ISSUE TITLE
How to create multiple independent components ?

### ISSUE THREAD

**Issue by GiorgosK** [redradix/svelte-custom-element-template#4]
Nice job so far on this template.

I can see that this template creates 1 custom element `<svelte:options tag="svelte-custom-element" />` that can be used as `<svelte-custom-element/>` but how will you set it up to have multiple components that each needs to have their own TAGNAME ?

**Comment by MonkeyAndres** [comment]
This component isn't sustainable for that, however you can do this by creating another repo with the template. Alternatives are:
- Change build script and bundle the other Svelte components as custom elements (you may have problems with nested normal Svelte components and styles)
- Don't use this template and do it from scratch with Svelte (you'll lose some ability to work with multiple nested components and transitions)

**Comment by GiorgosK** [comment]
Great thanks for the answer I was suspecting those 2 alternatives.
